---
title: "W6D2"
format: typst
---

# Goals for today

- Discuss the LOTF report with the class
- Discuss the criteria for your final project data sources
- Learn where and how to find good data sources that meet these criteria
------------------------------------------------------------------------

# Leading on Opportunity Task Force Report

- Time: 5 minutes

- **Task**: Talk with your teammates for a few minutes about your assigned question.

  1.  What are the impacts of segregation by race and income?
  2.  What are some of the historical contexts of segregation in Charlotte-Mecklenburg?
  3.  What is the current state of public schools in CMS in terms of segregation?
  4.  What's strategy A by the task force? Summarize some of its recommendations.
  5.  What is the task force's arguments for its solutions for high poverty schools?
  6.  Define a "zero-sum game" and its interaction with the recommendations.
  7.  What's strategy B by the task force? Summarize some of its recommendations.
  8.  Discuss whether the report surprises your team and whether this has been your own personal observations in the Charlotte-Mecklenburg area.

Each team will get to answer one question and share it with the class.

------------------------------------------------------------------------

# Data Selection

## Primary vs. secondary sources

- **Primary** sources are original, firsthand sources of data, typically collected or generated by a researcher or organization for a specific purpose.
- **Secondary** sources typically use primary sources and summarize them, transform them, or otherwise interpret them.

::: callout-tip
Much of the work we've done this semester would be considered "secondary analysis" because we've been using data gathered by Chetty, a primary researcher, or the Common Core Dataset from the Department of Education.
:::

## Examples of primary data sources

- Data collected by government agencies (Census Bureau, Bureau of Labor & Statistics)
- Data collected by academic researchers (Chetty, et al)
- Data collected by non-profit organizations (Urban Institute)

## Be careful with these data sources

- Kaggle
- Hugging Face
- Our World in Data
- data.world

::: callout-tip
There is some amazing data on these sites, but much of it is secondary!
:::

## Kaggle example

Link: [Science of Policing Equity](https://www.kaggle.com/code/shivamb/1-solution-workflow-science-of-policing-equity/notebook){target="_blank"}

## Our World in Data example

Link: [Our World in Data](https://ourworldindata.org/){target="_blank"}

Specific example: [Vaccination coverage](https://ourworldindata.org/grapher/global-vaccination-coverage?country=~USA){target="_blank"}

------------------------------------------------------------------------

# Data Conversations

- **Time**: 10 minutes

Get with your team, review your RQs from the project. Revisit the potential data sources that you listed and think about the feedback from the RQ activity we did in last class. Pick one specific RQ, if you have many, and narrow down your data source if you can.

**At the end of 10 minutes, one member of your team should be ready to stand up and discuss your RQ and the data sources you found!**

## Team Presentation

Each team gets **3 minutes** to present:

- In one sentence, remind everyone about the RQ you focused on for your team.
- What data sources did you find?
- What is your process of finding the dataset? Don't simply just say Googling or Claude/ChatGPT. Rather, you can talk about the strategy of finding this data.
- What challenges did you encounter when searching for this data?

::: callout-note
This is an activity to give the entire class an opportunity to learn from each other and see the opportunities out there.
:::
